#!/usr/bin/env python3
"""
🏭 Agentic Component Factory Tool (MVP)
Generates A2UI Component Scaffolding based on descriptions.

Usage:
  python tools/component_factory.py "A Kanban Board for Deal Flow" --type pane
"""

import argparse
import sys
import os
import json
import logging
from pathlib import Path
from typing import Dict, Any

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger("Factory")

class ComponentFactory:
    def __init__(self, output_dir: str = "src/components/generated"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        # Load registry if exists (mock for now)
        self.registry_path = Path("a2ui_integration/component_registry.json")
        
    def generate(self, description: str, component_type: str):
        """
        The Core Factory Method. 
        In the full version, this calls an LLM. 
        In this MVP, it uses rule-based templates.
        """
        logger.info(f"🏗️  Fabricating component: '{description}' ({component_type})")
        
        # 1. Generate Schema (JSON)
        schema = self._generate_schema(description, component_type)
        
        # 2. Generate Frontend (Fake React/Vue Wrapper)
        frontend_code = self._generate_frontend(schema)
        
        # 3. Save Artifacts
        self._save_artifacts(schema, frontend_code)
        
    def _generate_schema(self, description: str, component_type: str) -> Dict[str, Any]:
        """Generates the A2UI JSON Schema"""
        slug = description.lower().replace(" ", "_").replace("-", "_")[:20]
        
        if "kanban" in description.lower():
            return {
                "type": "pane",
                "id": f"s_{slug}",
                "layout": "horizontal",
                "panes": [
                     {"type": "pane", "title": "To Do", "cards": []},
                     {"type": "pane", "title": "In Progress", "cards": []},
                     {"type": "pane", "title": "Done", "cards": []}
                ]
            }
        elif "funnel" in description.lower():
            return {
               "type": "custom:funnel_chart",
               "id": f"c_{slug}",
               "properties": {
                   "stages": ["Lead", "Qualified", "Prosposal", "Closed"],
                   "values": [100, 50, 25, 10]
               }
            }
        else:
            # Generic Card
            return {
                "type": "card",
                "id": f"c_{slug}",
                "title": description,
                "content_blocks": [
                    {"type": "text", "content": f"Placeholder for {description}"}
                ]
            }

    def _generate_frontend(self, schema: Dict[str, Any]) -> str:
        """Generates the Frontend Code Wrapper"""
        component_id = schema.get("id", "component")
        # Note: We use double braces {{ }} to output literal braces for JS code
        return f"""
// Auto-generated by Agentic Component Factory
// ID: {component_id}
import React from 'react';
import {{ A2UIComponent }} from '@dhii/a2ui';

export const GeneratedComponent = ({{ data }}) => {{
  return (
    <div className="a2ui-generated-wrapper">
      {{/* Schema Driven Rendering */}}
      <A2UIComponent schema={{ {json.dumps(schema)} }} data={{data}} />
    </div>
  );
}};
"""

    def _save_artifacts(self, schema: Dict[str, Any], frontend_code: str):
        """Saves the generated files"""
        comp_id = schema.get("id")
        
        # Save Schema
        schema_path = self.output_dir / f"{comp_id}.json"
        with open(schema_path, "w") as f:
            json.dump(schema, f, indent=2)
        logger.info(f"✅ Schema saved: {schema_path}")
        
        # Save Frontend
        fe_path = self.output_dir / f"{comp_id}.tsx"
        with open(fe_path, "w") as f:
            f.write(frontend_code)
        logger.info(f"✅ Frontend saved: {fe_path}")

def main():
    parser = argparse.ArgumentParser(description="Agentic Component Factory")
    parser.add_argument("description", help="Natural language description of the component")
    parser.add_argument("--type", default="card", choices=["card", "pane", "app_shell"], help="Root component type")
    
    args = parser.parse_args()
    
    factory = ComponentFactory()
    factory.generate(args.description, args.type)

if __name__ == "__main__":
    main()
